import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { isIP } from "node:net";
import path from "node:path";
import { fileURLToPath } from "node:url";

const GENERATED_START = "<!-- CONTABIL-MM:SEO:START -->";
const GENERATED_END = "<!-- CONTABIL-MM:SEO:END -->";
const SITEMAP_MARKER = "<!-- Generated by scripts/build-seo.mjs -->";
const PAGE_DEFINITIONS = [
  { file: "index.html", label: "Início" },
  { file: "servicos.html", label: "Serviços" },
  { file: "sobre.html", label: "Sobre nós" },
  { file: "contato.html", label: "Contato" },
  { file: "privacidade.html", label: "Privacidade", optional: true },
];

function escapeMarkup(value) {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  })[character]);
}

function serializeSchema(value) {
  // Keep configured strings from closing a script element in the HTML parser.
  return JSON.stringify(value, null, 2)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function textField(value, field) {
  if (typeof value !== "string" || !value.trim() || value.length > 4000) {
    throw new Error(`O campo ${field} deve conter um texto válido.`);
  }
  return value.trim();
}

export function normalizeSiteUrl(value) {
  if (value === "") return "";
  if (typeof value !== "string" || value !== value.trim()) {
    throw new Error("siteUrl deve ser vazio ou conter a origem HTTPS definitiva do site.");
  }
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new Error("siteUrl inválido. Informe a origem HTTPS definitiva, sem caminho ou parâmetros.");
  }
  const hostname = url.hostname.toLowerCase();
  const isReserved = /(^|\.)(localhost|local|internal|test|invalid|example)$/.test(hostname);
  const isPreview = /(^|\.)(vercel\.app|netlify\.app|pages\.dev|github\.io)$/.test(hostname);
  if (url.protocol !== "https:" || url.username || url.password || url.port ||
      url.pathname !== "/" || url.search || url.hash || isIP(hostname.replace(/^\[|\]$/g, "")) ||
      !hostname.includes(".") || isReserved || isPreview ||
      !/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/.test(hostname)) {
    throw new Error("siteUrl deve ser um domínio HTTPS definitivo, sem IP, endereço local, domínio de preview, caminho ou parâmetros.");
  }
  return url.origin;
}

function validateConfig(config) {
  if (!config || typeof config !== "object" || Array.isArray(config)) {
    throw new Error("seo.config.json precisa conter um objeto de configuração.");
  }
  const origin = normalizeSiteUrl(config.siteUrl);
  const siteName = textField(config.siteName, "siteName");
  const token = config.searchConsoleVerification;
  if (typeof token !== "string" || (token !== "" && !/^[A-Za-z0-9_-]{1,256}$/.test(token))) {
    throw new Error("searchConsoleVerification deve ser vazio ou conter apenas o token de verificação do Google.");
  }
  if (!config.pages || typeof config.pages !== "object" || Array.isArray(config.pages)) {
    throw new Error("O campo pages deve conter os títulos e descrições das páginas.");
  }
  return { origin, siteName, token, pages: config.pages };
}

function pageUrl(origin, file) {
  return `${origin}/${file === "index.html" ? "" : file}`;
}

function businessSchema(origin) {
  const business = {
    "@type": "AccountingService",
    name: "Contabil MM",
    alternateName: "Assessoria Contábil MM",
    foundingDate: "1981",
    telephone: "+5511991001754",
    email: "contabilmm@yahoo.com.br",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Rua Treze de Maio, 582 — Vila Galvão",
      addressLocality: "Guarulhos",
      addressRegion: "SP",
      addressCountry: "BR",
    },
    areaServed: { "@type": "City", name: "Guarulhos" },
    hasMap: "https://www.google.com/maps/?cid=4580796176665174713",
    sameAs: ["https://www.instagram.com/contabilmm/"],
  };
  if (origin) {
    business["@id"] = `${origin}/#contabil-mm`;
    business.url = `${origin}/`;
    business.logo = `${origin}/assets/contabil-mm-logo.png`;
    business.image = `${origin}/assets/contabil-mm-logo.png`;
  }
  return business;
}

function metadataBlock(config, definition, title, description, newline) {
  const { origin, siteName, token } = config;
  const meta = (key, value, kind = "name") => `<meta ${kind}="${key}" content="${escapeMarkup(value)}">`;
  const lines = [
    GENERATED_START,
    `<title>${escapeMarkup(title)}</title>`,
    meta("description", description),
    meta("og:locale", "pt_BR", "property"),
    meta("og:site_name", siteName, "property"),
    meta("og:type", "website", "property"),
    meta("og:title", title, "property"),
    meta("og:description", description, "property"),
    meta("twitter:card", "summary"),
    meta("twitter:title", title),
    meta("twitter:description", description),
  ];
  if (origin) {
    lines.push(
      `<link rel="canonical" href="${escapeMarkup(pageUrl(origin, definition.file))}">`,
      meta("og:url", pageUrl(origin, definition.file), "property"),
      meta("og:image", `${origin}/assets/contabil-mm-logo.png`, "property"),
      meta("og:image:alt", "Logo da Contabil MM", "property"),
      meta("twitter:image", `${origin}/assets/contabil-mm-logo.png`),
    );
  }
  if (token) lines.push(meta("google-site-verification", token));

  const graph = [businessSchema(origin)];
  if (origin && definition.file === "index.html") {
    graph.push({
      "@type": "WebSite",
      "@id": `${origin}/#website`,
      name: siteName,
      url: `${origin}/`,
      inLanguage: "pt-BR",
      publisher: { "@id": `${origin}/#contabil-mm` },
    });
  } else if (origin) {
    graph.push({
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Início", item: `${origin}/` },
        { "@type": "ListItem", position: 2, name: definition.label, item: pageUrl(origin, definition.file) },
      ],
    });
  }
  lines.push(
    '<script type="application/ld+json">',
    serializeSchema({ "@context": "https://schema.org", "@graph": graph }).replace(/\n/g, newline),
    "</script>",
    GENERATED_END,
  );
  return lines.join(newline);
}

function replaceMetadata(html, block, file) {
  const headMatch = html.match(/<head\b[^>]*>([\s\S]*?)<\/head\s*>/i);
  if (!headMatch) throw new Error(`${file} não possui um elemento head válido.`);
  const head = headMatch[1];
  const starts = head.split(GENERATED_START).length - 1;
  const ends = head.split(GENERATED_END).length - 1;
  let newHead;
  if (starts || ends) {
    if (starts !== 1 || ends !== 1 || head.indexOf(GENERATED_START) > head.indexOf(GENERATED_END)) {
      throw new Error(`Bloco SEO inconsistente em ${file}. Verifique os delimitadores.`);
    }
    newHead = head.slice(0, head.indexOf(GENERATED_START)) + block +
      head.slice(head.indexOf(GENERATED_END) + GENERATED_END.length);
  } else {
    // Migrate only the former title/description; leave assets, scripts and other manual metadata intact.
    newHead = head.replace(/<title\b[^>]*>[\s\S]*?<\/title\s*>[\t ]*(?:\r?\n)?/gi, "")
      .replace(/<meta\b(?=[^>]*\bname\s*=\s*(["'])description\1)[^>]*>[\t ]*(?:\r?\n)?/gi, "");
    const newline = html.includes("\r\n") ? "\r\n" : "\n";
    newHead = `${newHead.trimEnd()}${newline}${block}${newline}`;
  }
  const index = headMatch.index + headMatch[0].indexOf(">") + 1;
  return html.slice(0, index) + newHead + html.slice(index + head.length);
}

/** Build static metadata for deployed HTML. An empty siteUrl intentionally emits no canonical or sitemap. */
export function buildSeo(rootDir) {
  const root = path.resolve(rootDir);
  const config = validateConfig(JSON.parse(readFileSync(path.join(root, "seo.config.json"), "utf8")));
  const updates = [];
  for (const definition of PAGE_DEFINITIONS) {
    const filename = path.join(root, definition.file);
    if (definition.optional && !existsSync(filename)) continue;
    const pageConfig = config.pages[definition.file];
    const title = textField(pageConfig?.title, `pages.${definition.file}.title`);
    const description = textField(pageConfig?.description, `pages.${definition.file}.description`);
    const html = readFileSync(filename, "utf8");
    const newline = html.includes("\r\n") ? "\r\n" : "\n";
    const block = metadataBlock(config, definition, title, description, newline);
    updates.push({ file: definition.file, content: replaceMetadata(html, block, definition.file) });
  }
  const robots = [
    "# Generated by scripts/build-seo.mjs",
    "User-agent: *",
    "Allow: /",
    "Disallow: /.reference/",
    "Disallow: /.git/",
    "Disallow: /scripts/",
    "Disallow: /tests/",
    "Disallow: /README.md",
    "Disallow: /seo.config.json",
    "Disallow: /package.json",
    "Disallow: /package-lock.json",
    "Disallow: /server.mjs",
  ];
  if (config.origin) robots.push(`Sitemap: ${config.origin}/sitemap.xml`);
  const sitemapPath = path.join(root, "sitemap.xml");
  const sitemap = config.origin ? [
    '<?xml version="1.0" encoding="UTF-8"?>',
    SITEMAP_MARKER,
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...updates.map(({ file }) => `  <url><loc>${escapeMarkup(pageUrl(config.origin, file))}</loc></url>`),
    "</urlset>",
    "",
  ].join("\n") : "";
  if (!sitemap && existsSync(sitemapPath) && !readFileSync(sitemapPath, "utf8").includes(SITEMAP_MARKER)) {
    throw new Error("Existe um sitemap.xml manual. Revise-o antes de gerar SEO sem domínio definitivo.");
  }
  // Validate every input before changing any generated file.
  for (const { file, content } of updates) writeFileSync(path.join(root, file), content, "utf8");
  writeFileSync(path.join(root, "robots.txt"), `${robots.join("\n")}\n`, "utf8");
  if (sitemap) writeFileSync(sitemapPath, sitemap, "utf8");
  else if (existsSync(sitemapPath)) unlinkSync(sitemapPath);
  return { pages: updates.map(({ file }) => file), siteUrl: config.origin, sitemap: Boolean(sitemap), searchConsoleConfigured: Boolean(config.token) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const result = buildSeo(path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."));
    console.log(`SEO atualizado em ${result.pages.length} páginas e robots.txt.`);
    if (result.siteUrl) console.log(`Domínio: ${result.siteUrl}. Sitemap gerado em sitemap.xml.`);
    else console.log("Pendente: preencha siteUrl em seo.config.json com o domínio HTTPS definitivo. Canonical, og:url e sitemap aguardam essa confirmação.");
    if (!result.searchConsoleConfigured) console.log("Opcional: preencha searchConsoleVerification com o token fornecido pelo Google Search Console.");
  } catch (error) {
    console.error(`Falha ao gerar SEO: ${error.message}`);
    process.exitCode = 1;
  }
}
